In [1]:
import tensorflow

# Load mnist Dataset

In [2]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels),(test_images, test_labels)=mnist.load_data()

# Define Architecture

In [6]:
from tensorflow.keras import models
from tensorflow.keras import layers
network =models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10,activation='softmax'))


# Compile Network

In [8]:
network.compile(optimizer='rmsprop',
               loss='categorical_crossentropy',
               metrics=['accuracy'])

# Preparing Data 

In [9]:
train_images[4]/255

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [10]:
# we done scalling to change the values between 0 to 1 tochnge its variation
# to done scalling we done the tensor with maximum value
train_images=train_images.reshape(60000,28*28)
train_images=train_images.astype("float32")/255
test_images=test_images.reshape(10000,28*28)
test_images=test_images.astype("float32")/255

In [11]:
train_images[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [12]:
from tensorflow.keras.utils import to_categorical
train_labels=to_categorical(train_labels)
test_labels=to_categorical(test_labels)
train_labels[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

### Train model:

In [13]:
network.fit(train_images,train_labels,epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 6s 95us/sample - loss: 0.2533 - acc: 0.9266
Epoch 2/5
60000/60000 [==============================] - 5s 88us/sample - loss: 0.1037 - acc: 0.9686
Epoch 3/5
60000/60000 [==============================] - 5s 89us/sample - loss: 0.0680 - acc: 0.9797
Epoch 4/5
60000/60000 [==============================] - 5s 89us/sample - loss: 0.0496 - acc: 0.9850
Epoch 5/5
60000/60000 [==============================] - 6s 92us/sample - loss: 0.0370 - acc: 0.9891


### Test model:

In [14]:
test_loss,test_acc=network.evaluate(test_images,test_labels)

10000/10000 [==============================] - 1s 111us/sample - loss: 0.0626 - acc: 0.9806
